In [21]:
#과제 3-1 : 행렬 삼칙연산(덧셈, 뺄셈, 곱셈) 계산기

import torch

def matrix_calculator(op, mat1, mat2) :
  # 덧셈 = 1, 뺄셈 = 2, 행렬곱 = 3

  if (mat1.size(dim=1) != mat2.size(dim=0)) and (op == 3) :
    print("you can't use this operator because those two operands can't be mutiplied.")

  elif op == 1 :
    result = mat1 + mat2
    print(result)

  elif op == 2 :
    result = mat1 - mat2
    print(result)

  elif op == 3 :
    result = torch.matmul(mat1, mat2)
    print(result)

  else :
    print("Wrong operator.")

matA = torch.Tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# (2, 5)
matB = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
# (5, 4)
matC = torch.Tensor([[1, 2], [3, 4], [5, 6]])
# (3, 2)
matD = torch.Tensor([[7, 8], [9, 10], [11, 12]])
# (3, 2)

matrix_calculator(1, matC, matD)
print(" ")
matrix_calculator(2, matC, matD)
print(" ")
matrix_calculator(3, matA, matB)
print(" ")
matrix_calculator(3, matA, matC)
print(" ")
matrix_calculator(4, matA, matD)

tensor([[ 8., 10.],
        [12., 14.],
        [16., 18.]])
 
tensor([[-6., -6.],
        [-6., -6.],
        [-6., -6.]])
 
tensor([[175., 190., 205., 220.],
        [400., 440., 480., 520.]])
 
you can't use this operator because those two operands can't be mutiplied.
 
Wrong operator.


In [32]:
#과제 3-2 : 정사각행렬을 가지고 놀아보기
# (1) 정사각행렬을 만들기

import torch

mat = torch.arange(16).reshape(4, 4)

mat

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [51]:
# (2-1) 90도 돌리기

'''
되어야 하는 상태 :
[12, 8, 4, 0],
[13, 9, 5, 1],
[14, 10, 6, 2],
[15, 11, 7, 3]

'''

mat90 = torch.flip(mat.T, [1])

mat90

tensor([[12,  8,  4,  0],
        [13,  9,  5,  1],
        [14, 10,  6,  2],
        [15, 11,  7,  3]])

In [52]:
# (2-2) 180도 돌리기

'''
되어야 하는 상태 :
[15,  14, 13,  12],
[11,  10,  9,   8],
[7,    6,  5,   4],
[3,    2,  1,   0]

'''

mat180 = torch.flip(mat, (1, 0))

mat180

tensor([[15, 14, 13, 12],
        [11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]])

In [53]:
# (2-3) 270도 돌리기

'''
되어야 하는 상태 :
[3,  7, 11, 15],
[2,  6, 10, 14],
[1,  5,  9, 13],
[0,  4,  8, 12]

'''
mat270 = torch.flip(mat, [1]).T

mat270

tensor([[ 3,  7, 11, 15],
        [ 2,  6, 10, 14],
        [ 1,  5,  9, 13],
        [ 0,  4,  8, 12]])

In [55]:
# (3) 뒤집기

'''
되어야 하는 상태 :
[ 3,  2,  1,  0],
[ 7,  6,  5,  4],
[11, 10,  9,  8],
[15, 14, 13, 12]

'''

mat_flip = torch.flip(mat, [1])

mat_flip

tensor([[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8],
        [15, 14, 13, 12]])